apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleep-monitor-deployment
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: sleep-monitor
  template:
    metadata:
      labels:
        app: sleep-monitor
    spec:
      containers:
        - name: sleep-monitor
          image: bach2690/sleep-monitor:latest
          ports:
            - containerPort: 3000
          env:
            - name: NEXTAUTH_URL
              value: "https://sleepmonitoring.org"
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: sleep-monitor-secrets
                  key: MONGO_URI
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: sleep-monitor-secrets
                  key: NEXTAUTH_SECRET
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: sleep-monitor-secrets
                  key: OPENAI_API_KEY
            - name: ESP32_API_KEY
              valueFrom:
                secretKeyRef:
                  name: sleep-monitor-secrets
                  key: ESP32_API_KEY

        - name: nginx-proxy
          image: bach2690/sleep-monitor-nginx:latest
          ports:
            - containerPort: 80
              hostPort: 80
            - containerPort: 443
              hostPort: 443
          securityContext:
            privileged: true
          volumeMounts:
            - name: certs
              mountPath: /etc/letsencrypt/live/sleepmonitoring.org
              readOnly: true
            - name: certbot-webroot
              mountPath: /var/www/certbot


      volumes:
        - name: certs
          hostPath:
            path: /etc/letsencrypt/archive/sleepmonitoring.org
            type: Directory
        - name: certbot-webroot
          hostPath:
            path: /var/www/certbot
            type: Directory




# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: sleep-monitor-deployment
# spec:
#   replicas: 1
#   strategy:
#     type: Recreate
#   selector:
#     matchLabels:
#       app: sleep-monitor
#   template:
#     metadata:
#       labels:
#         app: sleep-monitor
#     spec:
#       containers:
#         - name: sleep-monitor
#           image: bach2690/sleep-monitor:latest
#           ports:
#             - containerPort: 3000
#           env:
#             - name: NEXTAUTH_URL
#               value: "http://sleepmonitoring.org"
#             - name: MONGO_URI
#               valueFrom:
#                 secretKeyRef:
#                   name: sleep-monitor-secrets
#                   key: MONGO_URI
#             - name: NEXTAUTH_SECRET
#               valueFrom:
#                 secretKeyRef:
#                   name: sleep-monitor-secrets
#                   key: NEXTAUTH_SECRET
#             - name: OPENAI_API_KEY
#               valueFrom:
#                 secretKeyRef:
#                   name: sleep-monitor-secrets
#                   key: OPENAI_API_KEY
#             - name: ESP32_API_KEY
#               valueFrom:
#                 secretKeyRef:
#                   name: sleep-monitor-secrets
#                   key: ESP32_API_KEY

#         - name: nginx-proxy
#           image: bach2690/sleep-monitor-nginx:latest
#           ports:
#             - containerPort: 80
#             - containerPort: 443





              
