apiVersion: v1
kind: Service
metadata:
  name: sleep-monitor-service
spec:
  selector:
    app: sleep-monitor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 32000
  type: NodePort

