apiVersion: v1
kind: Service
metadata:
  name: sleep-monitor-service
spec:
  type: LoadBalancer
  selector:
    app: sleep-monitor
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443



