apiVersion: v1
kind: Service
metadata:
  name: sleep-monitor-service
spec:
  selector:
    app: sleep-monitor
  type: NodePort
  ports:
    - name: app
      protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32000


