apiVersion: v1
kind: Service
metadata:
  name: sleep-monitor-service
spec:
  selector:
    app: sleep-monitor
  type: NodePort
  ports:
    - name: https
      protocol: TCP
      port: 443           # Cluster IP port
      targetPort: 443     # Container (nginx) port
      nodePort: 32443     # EC2 NodePort (external)


